services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'likeit'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    ports:
      - "3306:3306"
